# Generated by Django 6.0.3 on 2026-04-01 20:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('category', models.CharField(choices=[('core', 'Core Competency'), ('leadership', 'Leadership Competency'), ('technical', 'Technical Competency'), ('functional', 'Functional Competency')], max_length=20)),
                ('description', models.TextField()),
                ('behavioral_indicators', models.TextField(blank=True, help_text='Describe observable behaviors per level')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Competencies',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='IndividualDevelopmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('career_objective', models.TextField(blank=True)),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_idps', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year'],
                'unique_together': {('user', 'year')},
            },
        ),
        migrations.CreateModel(
            name='IDPActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learning_intervention', models.CharField(max_length=300)),
                ('timeline', models.CharField(max_length=100)),
                ('success_indicator', models.TextField(blank=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competencies.competency')),
                ('idp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='competencies.individualdevelopmentplan')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeCompetency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_level', models.IntegerField(choices=[(1, 'Basic'), (2, 'Intermediate'), (3, 'Advanced'), (4, 'Expert')], default=1)),
                ('target_level', models.IntegerField(choices=[(1, 'Basic'), (2, 'Intermediate'), (3, 'Advanced'), (4, 'Expert')], default=2)),
                ('assessment_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessed_competencies', to=settings.AUTH_USER_MODEL)),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competencies.competency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competencies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'competency')},
            },
        ),
        migrations.CreateModel(
            name='PositionCompetency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=200)),
                ('required_level', models.IntegerField(choices=[(1, 'Basic'), (2, 'Intermediate'), (3, 'Advanced'), (4, 'Expert')], default=1)),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competencies.competency')),
            ],
            options={
                'unique_together': {('position', 'competency')},
            },
        ),
    ]
