# Generated by Django 5.1.4 on 2026-04-13 07:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_privacy_erasure'),
        ('competencies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_title', models.CharField(max_length=200)),
                ('salary_grade', models.IntegerField(blank=True, null=True)),
                ('employment_status', models.CharField(blank=True, max_length=50)),
                ('office_unit', models.CharField(blank=True, help_text='Office / organizational unit', max_length=200)),
                ('immediate_supervisor', models.CharField(blank=True, max_length=200)),
                ('duties_and_responsibilities', models.TextField(help_text='List of duties and responsibilities')),
                ('performance_standards', models.TextField(blank=True, help_text='Key performance standards / targets')),
                ('education', models.TextField(blank=True)),
                ('training', models.TextField(blank=True)),
                ('experience', models.TextField(blank=True)),
                ('eligibility', models.TextField(blank=True, help_text='Civil Service Eligibility')),
                ('knowledge_skills_abilities', models.TextField(blank=True, help_text='Knowledge, Skills, and Abilities (KSAs) required')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_job_descriptions', to=settings.AUTH_USER_MODEL)),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.division')),
            ],
            options={
                'verbose_name': 'Job Description',
                'verbose_name_plural': 'Job Descriptions',
                'ordering': ['position_title'],
            },
        ),
        migrations.CreateModel(
            name='JobAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_date', models.DateField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, help_text='Summary of job analysis findings and methodology')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('finalized', 'Finalized'), ('applied', 'Applied to Position')], default='draft', max_length=20)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analyzed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_job_analyses', to=settings.AUTH_USER_MODEL)),
                ('applied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_job_analyses', to=settings.AUTH_USER_MODEL)),
                ('job_description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='competencies.jobdescription')),
            ],
            options={
                'verbose_name': 'Job Analysis',
                'verbose_name_plural': 'Job Analyses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobAnalysisCompetency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_level', models.IntegerField(choices=[(1, 'Basic'), (2, 'Intermediate'), (3, 'Advanced'), (4, 'Expert')], default=1)),
                ('justification', models.TextField(blank=True, help_text='Basis for requiring this competency at the specified level')),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competencies.competency')),
                ('job_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competency_mappings', to='competencies.jobanalysis')),
            ],
            options={
                'ordering': ['competency__category', 'competency__name'],
                'unique_together': {('job_analysis', 'competency')},
            },
        ),
    ]
