# Generated by Django 5.1.4 on 2026-04-13 08:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competencies', '0002_add_job_description_and_job_analysis'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobAnalysisEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('position_title', models.CharField(max_length=200)),
                ('office_service_division', models.CharField(blank=True, max_length=200)),
                ('section_project_unit', models.CharField(blank=True, max_length=200)),
                ('alternate_position', models.CharField(blank=True, max_length=200)),
                ('job_purpose', models.TextField(blank=True)),
                ('main_duties', models.TextField(blank=True)),
                ('challenges_critical_issues', models.TextField(blank=True)),
                ('additional_comments', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted')], default='draft', max_length=20)),
                ('certified_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_analysis_form_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job Analysis Form Entry',
                'verbose_name_plural': 'Job Analysis Form Entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequiredSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('skill_name', models.CharField(max_length=300)),
                ('proficiency_level', models.CharField(choices=[('basic', 'Basic'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('superior', 'Superior')], max_length=20)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_skills', to='competencies.jobanalysisentry')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SecondaryDuty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('task', models.TextField()),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('periodically', 'Periodically / As Instructed')], max_length=20)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondary_duties', to='competencies.jobanalysisentry')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ToolEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('name', models.CharField(max_length=300)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tools_equipment', to='competencies.jobanalysisentry')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
