# Generated by Django 5.1.4 on 2026-04-13 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competencies', '0003_add_job_analysis_entry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='jobanalysisentry',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jaf_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobanalysisentry',
            name='approved_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobanalysisentry',
            name='rejection_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobanalysisentry',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jaf_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobanalysisentry',
            name='reviewed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobanalysisentry',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted — Awaiting Supervisor Review'), ('reviewed', 'Reviewed — Awaiting Director Approval'), ('approved', 'Approved'), ('rejected', 'Returned for Revision')], default='draft', max_length=20),
        ),
    ]
