# Generated by Django 5.1.4 on 2026-04-13 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competencies', '0004_jaf_approval_workflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobanalysisentry',
            name='supervisor_created',
            field=models.BooleanField(default=False),
        ),
    ]
