# Generated by Django 5.1.4 on 2026-04-14 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competencies', '0008_jafrevisioncomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeecompetency',
            name='jaf_entry',
            field=models.ForeignKey(blank=True, help_text='The approved JAF that created/updated this entry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='synced_competencies', to='competencies.jobanalysisentry'),
        ),
        migrations.AddField(
            model_name='employeecompetency',
            name='source',
            field=models.CharField(choices=[('manual', 'Manually Assessed'), ('jaf', 'From Job Analysis Form')], default='manual', help_text='How this competency entry was created', max_length=10),
        ),
    ]
