# Generated by Django 5.1.4 on 2026-04-20 21:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competencies', '0009_employeecompetency_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DOTrCompetency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('core', 'Core Competency'), ('leadership', 'Leadership Competency'), ('functional', 'Functional Competency')], max_length=20)),
                ('description', models.TextField(blank=True, help_text='One-line definition / tagline shown below the name')),
                ('office', models.CharField(blank=True, help_text='For functional competencies — the Office/Service/Division this applies to', max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dotr_competencies_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'DOTr Competency',
                'verbose_name_plural': 'DOTr Competencies',
                'ordering': ['type', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DOTrCompetencyIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(choices=[(1, 'Basic'), (2, 'Intermediate'), (3, 'Advanced'), (4, 'Superior')])),
                ('indicator_number', models.CharField(blank=True, help_text='e.g. 1.1, 2.3', max_length=10)),
                ('description', models.TextField()),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='competencies.dotrcompetency')),
            ],
            options={
                'verbose_name': 'DOTr Competency Indicator',
                'verbose_name_plural': 'DOTr Competency Indicators',
                'ordering': ['level', 'order'],
            },
        ),
    ]
