# Generated by Django 5.1.4 on 2026-04-21 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competencies', '0010_dotr_competency_framework'),
    ]

    operations = [
        migrations.CreateModel(
            name='DOTrOfficeUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('unit_type', models.CharField(choices=[('service', 'Service'), ('division', 'Division'), ('unit', 'Unit'), ('section', 'Section'), ('office', 'Office')], default='division', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'DOTr Office Unit',
                'verbose_name_plural': 'DOTr Office Units',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='dotrcompetency',
            name='office',
            field=models.CharField(blank=True, help_text='Legacy text field; auto-synced from office_unit when set', max_length=200),
        ),
        migrations.CreateModel(
            name='DOTrOfficeMandate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('description', models.TextField()),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mandates', to='competencies.dotrofficeunit')),
            ],
            options={
                'verbose_name': 'DOTr Office Mandate',
                'verbose_name_plural': 'DOTr Office Mandates',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='dotrcompetency',
            name='office_unit',
            field=models.ForeignKey(blank=True, help_text='For functional competencies — the Office/Service/Division this applies to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competencies', to='competencies.dotrofficeunit'),
        ),
    ]
