# Generated by Django 5.1.4 on 2026-04-21 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_orgunit_head_user'),
        ('competencies', '0011_dotr_office_unit_mandates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dotrofficemandate',
            name='office',
        ),
        migrations.RemoveField(
            model_name='dotrcompetency',
            name='office_unit',
        ),
        migrations.AddField(
            model_name='dotrcompetency',
            name='division',
            field=models.ForeignKey(blank=True, help_text='For functional competencies — the Division/Office this applies to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dotr_competencies', to='accounts.division'),
        ),
        migrations.AddField(
            model_name='dotrofficemandate',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mandates', to='accounts.division'),
        ),
        migrations.AlterField(
            model_name='dotrcompetency',
            name='office',
            field=models.CharField(blank=True, help_text='Synced from division.name for easy querying', max_length=200),
        ),
        migrations.DeleteModel(
            name='DOTrOfficeUnit',
        ),
    ]
