# Generated by Django 6.0.3 on 2026-04-02 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='DOTR Official Certificate', max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='The active template is used for all new certificates.')),
                ('header_text', models.CharField(default='Department of Transportation', max_length=300)),
                ('subheader', models.CharField(default='Republic of the Philippines', max_length=300)),
                ('logo_left', models.ImageField(blank=True, help_text='Left logo (DOTR seal)', null=True, upload_to='cert_templates/')),
                ('logo_right', models.ImageField(blank=True, help_text='Right logo (optional)', null=True, upload_to='cert_templates/')),
                ('intro_line', models.CharField(default='This is to certify that', max_length=300)),
                ('body_after', models.TextField(blank=True, default='has successfully completed the training program')),
                ('footer_note', models.TextField(blank=True, default="This certificate is issued in recognition of the employee's commitment to professional excellence and continuous learning.")),
                ('signatory1_name', models.CharField(default='', max_length=200)),
                ('signatory1_position', models.CharField(default='Human Resource Management Officer', max_length=200)),
                ('signatory1_label', models.CharField(default='Issued by', max_length=100)),
                ('signatory2_name', models.CharField(blank=True, max_length=200)),
                ('signatory2_position', models.CharField(blank=True, max_length=200)),
                ('signatory2_label', models.CharField(blank=True, max_length=100)),
                ('orientation', models.CharField(choices=[('landscape', 'Landscape'), ('portrait', 'Portrait')], default='landscape', max_length=10)),
                ('primary_color', models.CharField(default='#003087', help_text='Hex color e.g. #003087', max_length=7)),
                ('accent_color', models.CharField(default='#FDB913', help_text='Hex color e.g. #FDB913', max_length=7)),
                ('background_color', models.CharField(default='#FFFFFF', max_length=7)),
                ('border_style', models.CharField(choices=[('classic', 'Classic Double Border'), ('modern', 'Modern Single Line'), ('minimal', 'Minimal'), ('ribbon', 'Ribbon Band')], default='classic', max_length=20)),
                ('show_score', models.BooleanField(default=True)),
                ('show_duration', models.BooleanField(default=True)),
                ('show_cert_number', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_active', '-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='certificate',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='certificates.certificatetemplate'),
        ),
    ]
