# Generated by Django 6.0.3 on 2026-04-14 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_certificatetemplate_certificate_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificatetemplate',
            name='accent_color',
            field=models.CharField(default='#b8860b', help_text='Gold accent — hex color', max_length=7),
        ),
        migrations.AlterField(
            model_name='certificatetemplate',
            name='body_after',
            field=models.TextField(blank=True, default='for his/her successful participation and completion of'),
        ),
        migrations.AlterField(
            model_name='certificatetemplate',
            name='footer_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='certificatetemplate',
            name='intro_line',
            field=models.CharField(default='is proudly presented to', max_length=300),
        ),
        migrations.AlterField(
            model_name='certificatetemplate',
            name='logo_right',
            field=models.ImageField(blank=True, help_text='Right logo (PH flag)', null=True, upload_to='cert_templates/'),
        ),
        migrations.AlterField(
            model_name='certificatetemplate',
            name='signatory1_label',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='certificatetemplate',
            name='signatory1_position',
            field=models.CharField(default='Director IV for Administrative Service concurrent\nManagement Information Systems Service', max_length=200),
        ),
    ]
