# Generated by Django 5.1.4 on 2026-04-14 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
        ('trainings', '0003_trainingrequest_status_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='module',
            field=models.OneToOneField(blank=True, help_text='The module this quiz is attached to (Module Quiz only).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz', to='trainings.trainingmodule'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='role',
            field=models.CharField(choices=[('module_quiz', 'Module Quiz'), ('final_exam', 'Final Exam')], default='final_exam', help_text='Module Quiz fires after the linked module; Final Exam fires after all modules.', max_length=20),
        ),
    ]
